# -*- coding: utf-8 -*-
"""variable and data types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVTCcpMtTW-M40dGNKf17E0XEYAzbsqB

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Variáveis & Tipos de Dados
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Introdução ao Google Colab;</li>
  <li>Variáveis;</li>
  <li>Números;</li>
  <li><i>Strings;</i></li>
  <li>Boleanos.</li>
</ol>

---

# **Exercícios**

## 1\. Google Colab

Crie uma célula de código que escreva o texto "Olá mundo!", utilize o comando `print`.
"""

print('Olá Mundo!')

"""# Nova seção

---

## 2\. Números

Preencha as células de código para preencher os valores de (A), (B) e (C) na tabela de ticket médio abaixo:

<br>

| Dia   | Valor Total Vendas | Qtd Total Vendas | Ticket Medio |
|-------|--------------------|------------------|--------------|
| 19/01 | (A)                | 3                | 320.52       |
| 20/01 | 834.47             | (B)              | 119.21       |
| 23/01 | 15378.12           | 5                | (C)          |
"""

# (A)
qtd_total_vendas_19 = 3
ticket_medio_19 = 320.52
valor_total_vendas_19 = ticket_medio_19 * qtd_total_vendas_19
print(valor_total_vendas_19)

# (B)
valor_total_vendas_20 = 834.47
ticket_medio_20 = 119.21
qtd_total_vendas_20 = valor_total_vendas_20 / ticket_medio_20
print(int(qtd_total_vendas_20))

# (C)
valor_total_vendas_23 = 15378.12
qtd_total_vendas_23 = 5
ticket_medio_23 = valor_total_vendas_23 / qtd_total_vendas_23
print(round(ticket_medio_23, 4))

"""---

## 3\. Strings

Aplique três métodos distintos na *string* abaixo, você pode conferir alguns métodos neste [link](https://www.w3schools.com/python/python_ref_string.asp):
"""

cancao = 'Roda mundo, roda gigante, roda moinho, roda pião.'

print(cancao.find("mundo"))
print(cancao.replace("mundo", "pequena"))
print(cancao.upper())

"""Extraia da string abaixo o valor da taxa **selic** na variável `selic` e o valor do **ano** na variavel `ano`. Imprima os valores na tela."""

noticia = 'Selic vai a 2,75% e supera expectativas; é a primeira alta em 6 anos.'

# encontrando a posição do 2,75% (valor da taxa selic)
print(noticia.find("2"))

# valor da taxa selic
selic = noticia[13:18]
print(selic)

# encontrando a posição do valor do ano
print(noticia.find("6"))

# valor do ano
ano = noticia[63:69]
print(ano)

"""---

## 4\. Booleanos

Utilize a tabela da verdade para responder: qual o valor da variável x?
"""

a = False
b = True

x = not a & b

a = False
b = True

x = not a & b

# not a é True porque a é false e b é True, logo, True & True é True
print(True & True)